version: '3.8'

services:
  chat-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=8080
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - chat-network

  # Optional: Local MongoDB for development
  mongo:
    image: mongo:7.0
    container_name: chat-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
    networks:
      - chat-network

  # Optional: Frontend container (if you have a separate frontend app)
  frontend:
    image: nginx:alpine
    container_name: chat-frontend
    ports:
      - "3000:80"
    volumes:
      - ./example-frontend:/usr/share/nginx/html
    depends_on:
      - chat-server
    networks:
      - chat-network

volumes:
  mongo_data:

networks:
  chat-network:
    driver: bridge