version: '3.8'

services:
  # Backend API Server
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=8080
    restart: unless-stopped
    networks:
      - chat-network

  # Frontend React App  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - chat-network

  # Optional: Local MongoDB for development
  # Uncomment if you want to use local MongoDB instead of Atlas
  # mongo:
  #   image: mongo:7.0
  #   container_name: chat-mongo
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=password123
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - chat-network

volumes:
  mongo_data:

networks:
  chat-network:
    driver: bridge